### ISSUE TITLE
tutorial for python version NEURON

### ISSUE THREAD

**Issue by ka711** [QBI-Software/NEURON-tutorial#1]
Hi, this is Kazutaka 
I'm learning NEURON for single and network modeling right now, and I noticed that the main interpreter for NEURON is the python (hoc seems to be deprecated)
Is it possible to replace the tutorial for python version because the current tutorial is written for hoc code?

**Comment by lizcw** [comment]
Hi Kazutaka, Sorry this is no longer being maintained. However, you are welcome to fork your own version and update it as needed. Regards, Liz
